### ISSUE TITLE
why 2PC on read-only foreign transaction in commit 77c8995?

### ISSUE THREAD

**Issue by luyang177** [pgfdwplus/postgres_fdw_plus#6]
you mentioned

> However the logic to determine whether foreign transaction is
write or read-only had a serious problem

what problem?

**Comment by MasaoFujii** [comment]
@luyang177 
The previous logic of determining whether 2PC is necessary based solely on the type of query being issued (such as SELECT) may not be sufficient as some SELECT queries may still generate WAL records and modify the database on the remote server. For example, a SELECT query on a foreign table "ft" (please see the following example) that causes a SELECT query on a view "t" on the remote server can generate WAL records, even though it may appear to be a read-only query.

While this kind of scenario may be rare, the logic basically needs to take it into consideration.

```
[REMOTE]
create view t as select pg_logical_emit_message(true, 'a', 'b') as x;

[LOCAL]
create foreign table ft (x pg_lsn) server loopback options (table_name 't');
```

**Comment by luyang177** [comment]
@MasaoFujii 
Okay, I see. That's indeed tricky, are there any other case?

**Comment by MasaoFujii** [comment]
@luyang177 
> That's indeed tricky, are there any other case?

I'm not certain if such cases exist in practice, but I can imagine scenarios where foreign tables reference user-defined functions that generate WAL records on the remote server, or where preloaded extensions, such as an insert audit log, cause WAL records to be generated during the execution of SELECT queries.
